# Generated by Django 4.2.18 on 2025-03-13 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
