# Generated by Django 4.2.18 on 2025-03-15 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='social_app.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
