# Generated by Django 4.2.18 on 2025-04-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0011_post_total_likes_post_social_app__total_l_a271d6_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
